### ISSUE TITLE
Clarify timezone issues

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/advent#14]
`advent` file says:

> The site is programmed for Madrid's time

I think it's wrong.

> \<uzl\> AlexDaniel: To what timezone is the P6 Advent WP set?
> \<AlexDaniel\> uzl: I really don't know, but I think it works based on your timezone
> \<AlexDaniel\> so I'm in UTC+2 and I had to schedule it for 02:00 AM

**Comment by JJ** [comment]
What's wrong? Do you think it's better to set it to somewhere else? As long
as everyone knows the time zone, it's just a matter of offsets, right?

**Comment by AlexDaniel** [comment]
It's not set to anything. It is based on the local timezone of the author. That's how I understand the situation.

**Comment by JJ** [comment]
I don't think so. There's a single timezone defined for the whole site. I just found Madrid easier to understand than UTC (which was where it was set before)

**Comment by AlexDaniel** [comment]
If anything, set it back to UTC, please. Madrid is UTC+1, which is disorienting. Working with open source I have UTC time shown right next to the local time, and I'm sure that I'm not the only one who does stuff based on UTC.

But nonetheless, I had to set my article for 02:00 AM to schedule it for publishing on 00:00 UTC. It feels like it uses your local time, somehow.

**Comment by JJ** [comment]
Done.
