### ISSUE TITLE
20th anniversary advent needs example article

### ISSUE THREAD

**Issue by Altai-man** [Raku/advent#48]
Hi, @JJ.
Can instructions on RFC advent be made a bit more clear?

For example, I go to https://raku.org/archive/rfc/by-group.html and see some of RFCs are blue-ish, some are red-ish and some items have no background. Status:Frozen?

I think it will help people to participate to give a bit more detailed explanation on what is requested.

Also, while usual Advent posts have plenty of examples and semi-free blog post structure, it is not clear how those can be organized. Is it possible for you to post your article soon-ish so that people could copy-cat at least the overall structure instead of inventing wheels?

Thanks.

**Comment by JJ** [comment]
OK, I'll try. And yes, I'll try to do that, possibly this weekend.
