### ISSUE TITLE
Status of current year

### ISSUE THREAD

**Issue by zaucker** [Raku/advent#77]
I can't really figure out which slots/days are still open for the current year (2020). May be it could be mentioned in the README how/where to find that info?

**Comment by zaucker** [comment]
Oh, I just figured out that https://github.com/Raku/advent/blob/master/CONTRIBUTING.md is meant to do that. However, currently this links to the 2019 schedule (and there seems to be no 2020 schedule yet).
And the README also has a direct link to the 2019 schedule.

**Comment by JJ** [comment]
There are still 3 slots open, but this year we're not preassigning a day. If you want to contribute, add yourself to the [authors file](https://github.com/Raku/advent/blob/master/raku-advent-2020/authors.md) and get your article ready as soon as possible. We'll revise it, and then schedule it for publication.
But right, we should revise all that.
